export enum ErrorCode {
  DATABASE_ERROR = 'DATABASE_ERROR',
  DATABASE_RECORD_NOT_FOUND = 'DATABASE_RECORD_NOT_FOUND',
  DATABASE_UNIQUE_CONSTRAINT = 'DATABASE_UNIQUE_CONSTRAINT',
  DATABASE_FOREIGN_KEY_CONSTRAINT = 'DATABASE_FOREIGN_KEY_CONSTRAINT',
  PRODUCT_ALREADY_ACTIVE = 'PRODUCT_ALREADY_ACTIVE',
  PRODUCT_ALREADY_INACTIVE = 'PRODUCT_ALREADY_INACTIVE',
  PRODUCT_DEACTIVATED_CANNOT_EDIT = 'PRODUCT_DEACTIVATED_CANNOT_EDIT',
}
